### ISSUE TITLE
Factorization scale is not computed correctly

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/pineappl#101]
- The factorizations scales for `NMC_NC_EM_P_F2` are bugged and I don't understand why
- as we're in DIS Q2 = muF2
- in the observable card we have for the last bin `Q2: 99.03` - see https://github.com/NNPDF/runcards/blob/58c13d69787fc35cfd7f3ca9091f08ef1608ebf0/nnpdf31_proc/NMC_NC_EM_P_F2/observable.yaml#L837
- and this is also reflected in the grid:
```
$ pineappl convolute data/grids/200-NMC_NC_EM_P_F2.pineappl.lz4 NNPDF40_nnlo_as_01180
LHAPDF 6.4.0 loading /usr/share/lhapdf/LHAPDF/NNPDF40_nnlo_as_01180/NNPDF40_nnlo_as_01180_0000.dat
NNPDF40_nnlo_as_01180 PDF set, member #0, version 1                                                      
bin     Q2            x           F2p      scale uncertainty
---+-----+-----+------+------+------------+--------+--------
  0  0.16  0.16 0.0015 0.0015 1.7642563e-2 -105.85%  576.52%      
[...]
259 99.03 99.03  0.675  0.675 2.2627258e-2  -23.83%   39.32%
```
- but this is *not* reflected by the subgrids command:
```
$ pineappl subgrids --muf data/grids/200-NMC_NC_EM_D_F2.pineappl.lz4
o  b  l   muf
-+---+--+-----
[...]
3 259 10 9.951
```
- and this is also *not* reflected in `Grid.axes` https://github.com/N3PDF/pineappl/blob/725e4109c2b9f90cc883abd251c190409fe9f22c/pineappl/src/grid.rs#L1222 
  called via https://github.com/NNPDF/fktables/blob/7f34897005a90a6bcca38bf45a90b8dfb599dc99/fkutils/builder.py#L133 
  leading eventually to
```
$ cat data/operators_cards/NMC_NC_EM_P_F2.yaml
Q2grid:
- 26.07
[...]
- 99.03
```
- and so finally resulting in
```
$ python build.py 
┌───────────────┐
│ Computing ... │
└───────────────┘
   /media/FK/fktables/data/grids/200-NMC_NC_EM_D_F2.pineappl.lz4
 + /media/FK/fktables/data/operators/200-NMC_NC_EM_D_F2.tar
 = /media/FK/fktables/data/fktables/200-NMC_NC_EM_D_F2.pineappl.lz4
[00:00:00] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░      14/40040   - ETA: 00:00:00 
thread '<unnamed>' panicked at 'Couldn't find q2: 0.16 with xir: 1.0 and muf2_grid: [26.07, 26.36, 26.49, 26.52, 26.55, 26.6, 26.61, 26.63, 26.64, 34.74, 35.28, 35.32, 35.37, 35.4, 35.42, 35.43, 35.45, 35.5, 35.57, 44.94, 46.95, 46.98, 47.01, 47.03, 47.12, 47.16, 47.26, 63.04, 63.23, 63.48, 63.52, 63.53, 63.56, 63.65, 90.68, 96.35, 98.05, 98.82, 99.03]', /home/pineappl/pineappl/pineappl/src/grid.rs:1519:33
Traceback (most recent call last):
  File "/media/FK/fktables/build.py", line 109, in <module>
    b.build_fktables(pdf)
  File "/media/FK/fktables/fkutils/builder.py", line 226, in build_fktables
    pineko.convolute(grid, operator_path.resolve(), fktable_path, pdf)
  File "/media/FK/pineko/src/pineko/__init__.py", line 116, in convolute
    fktable = pineappl_grid.convolute_eko(operators, "evol", order_mask=order_mask_qcd)
  File "/media/FK/env/lib/python3.10/site-packages/pineappl/grid.py", line 270, in convolute_eko
    self.raw.convolute_eko(
pyo3_runtime.PanicException: Couldn't find q2: 0.16 with xir: 1.0 and muf2_grid: [26.07, 26.36, 26.49, 26.52, 26.55, 26.6, 26.61, 26.63, 26.64, 34.74, 35.28, 35.32, 35.37, 35.4, 35.42, 35.43, 35.45, 35.5, 35.57, 44.94, 46.95, 46.98, 47.01, 47.03, 47.12, 47.16, 47.26, 63.04, 63.23, 63.48, 63.52, 63.53, 63.56, 63.65, 90.68, 96.35, 98.05, 98.82, 99.03]
```
(of course the very same in proton and deuteron)

Any ideas on your side?

**Comment by cschwan** [comment]
@felixhekhorn `subgrid --muf` prints the *unsquared* factorization scale, so `9.951 * 9.951 = 99.022401` which is much closer to the desired value (the last digit might be off due to rounding). Should I also add `--muf2` and `--mur2` options to print the squared values?

**Comment by felixhekhorn** [comment]
> @felixhekhorn `subgrid --muf` prints the _unsquared_ factorization scale, so `9.951 * 9.951 = 99.022401` which is much closer to the desired value (the last digit might be off due to rounding). Should I also add `--muf2` and `--mur2` options to print the squared values?

ok, I see - yes, please, if that is not a big effort a `--muf2` would be appreciated

**Comment by cschwan** [comment]
It seems that the EKO is incomplete. Here's the relevant piece of code:

https://github.com/N3PDF/pineappl/blob/ca86b939d74707e1197c4cfa8387f1fd3402921e/pineappl/src/grid.rs#L1512-L1524

These lines search `eko_info` for the proper factorization scale value, but this object comes from outside so there's something wrong at a higher level. But also this method needs proper error handling; see https://github.com/N3PDF/pineappl/issues/85.

**Comment by felixhekhorn** [comment]
> It seems that the EKO is incomplete

true, but we use `axes` to determine which EKOs we actually need - so the problem is there

```
In [1]: import pineappl

In [2]: g = pineappl.grid.Grid.read("200-NMC_NC_EM_D_F2.pineappl.lz4")

In [3]: g.axes()
Out[3]: 
[...]
[26.07,
  26.36,
  26.49,
  26.52,
[...]
```

**Comment by cschwan** [comment]
Ah :smile: I see, so this comes full circle... I'll have a look at it!

**Comment by cschwan** [comment]
@felixhekhorn please try it again with commit e91a7df606e3cc36f52108545319c94a267456a9.

**Comment by felixhekhorn** [comment]
yes, seemed to have done the trick:
 ```
[0.16,                                                                                                  │   Compiling pyo3-macros v0.14.5
  0.17,                                                                                                  │   Compiling thiserror v1.0.30
  0.25,                                                                                                  │   Compiling ndarray v0.15.4
  0.26,                                                                                                  │   Compiling bincode v1.3.3
  0.35,                                                                                                  │   Compiling numpy v0.14.1
  0.36,                                                                                                  │   Compiling pineappl v0.5.0-beta.6 (/media/FK/pineappl/pineappl)
  0.45,                                                                                                  │   Compiling pineappl_py v0.5.0-beta.6 (/media/FK/pineappl/pineappl_py)
  0.46,                                                                                                  │    Finished release [optimized] target(s) in 18.96s
  0.6, 
```
(aaa tmux mess - don't worry ;-) )

**Comment by felixhekhorn** [comment]
@AleCandido I'm rerunning the EKOs at the moment, though only one of them - the other one can be linked since they are identical

**Comment by AleCandido** [comment]
Ok, thank you very much :D
