### ISSUE TITLE
Update webpage

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#116]
We have a webpage at https://n3pdf.github.io/pineappl/ using gh-pages and we should update it!

**Comment by cschwan** [comment]
@felixhekhorn I agree with every point, that's a very good list. I wonder whether we shouldn't have a single homepage for each of our tools but instead one homepage for all of them; you already mentioned runcards, which uses also yadism and then we have of course also EKO and PinEKO.

This homepage would then mainly serve as an overview and explain what is what, where you can read details and showcase a few examples.

**Comment by AleCandido** [comment]
@cschwan I believe we can do both:
- individual home pages for the tools, that are more frequently updated (e.g.: at relevant releases) and contain tool-specific information
- a toolchain home page, with overall information and tools description (but without technical information, e.g. about CLI and installation), redirecting to the individual home pages

**Comment by felixhekhorn** [comment]
> have a single homepage

Mmm, not so sure, because that one would be bloated - look at the list, this is already quite some stuff; and for eko I expect a similar order of magnitude, since we want to use that one e.g. to show more benchmark plots

> we can do both

agreed

**Comment by cschwan** [comment]
I made a small change: when you go to our homepage <https://n3pdf.github.io/pineappl/> it'll no longer show a markdown file from `gh-pages`, which was completely outdated, but rather the README.md from master. Alternatively we could show docs/README.md, which might be better. In any case the homepage should be automatically much better maintained now.

**Comment by AleCandido** [comment]
> * the link to `CONTRIBUTING` on the website is served as a file and not as a redirect to a page

This I don't fully understand why, maybe try with `[...](./CONTRIBUTING.md)`?

**Comment by cschwan** [comment]
The problems with the website I collect here: https://github.com/N3PDF/pineappl/issues/146.

**Comment by cschwan** [comment]
@felixhekhorn I'm thinking of reworking the README a bit, as it's the first impression. I think the best would be show some nice plots and tables to show off what PineAPPL can do.

**Comment by felixhekhorn** [comment]
> @felixhekhorn I'm thinking of reworking the README a bit, as it's the first impression. I think the best would be show some nice plots and tables to show off what PineAPPL can do.

that's a good idea - however, there is a trade off to be made: how much to show on the front-page without make it bloated? (on a separate page one can be as detailed as one likes)

**Comment by cschwan** [comment]
I believe most points have been addressed. Please open a new Issue if that's not the case.
