### ISSUE TITLE
Add new switch to `convolute` subcommand to multiply with factors

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#124]
We need the possibility to easily multiply the convoluted results with some factors, see for instance https://github.com/NNPDF/fktables/issues/23#issuecomment-1061591595.

**Comment by cschwan** [comment]
This really isn't the job of PineAPPL, we should use `R`, `numpy` or similar tools/libaries for that.

**Comment by AleCandido** [comment]
I guess we can just consider to expose more API to also modify the grid (at the moment is possible to cut bins, but I don't know about anything else).

**Comment by cschwan** [comment]
In the meantime we have `Grid::scale_by_bin`, but I'm not sure there's a Python wrapper yet.
