### ISSUE TITLE
(Re-)enable fastNLO converter in the CI again

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#127]
cargo+tarpaulin can't compile the fastNLO converter in the CI, probably due to a problem described in this Issue: https://github.com/xd009642/tarpaulin/issues/517. The failed CI run is available here: https://github.com/N3PDF/pineappl/actions/runs/1992743663.

**Comment by AleCandido** [comment]
Still failing, since it's still attempting to compile `pineappl_fastnlo` https://github.com/N3PDF/pineappl/actions/runs/1992888567

**Comment by cschwan** [comment]
Try no. 2 with commit 44526d3075b2d9ef90d36d5dd23ac54526f6296a.

**Comment by cschwan** [comment]
To make explicit what I've implicitly wrote above: it works on my local computer. Now I'm going through the check list in https://github.com/xd009642/tarpaulin/issues/517#issuecomment-923449246.

**Comment by cschwan** [comment]
Using `grcov` is finally working with commit 0fc2757f1d012cc67609834302aac79933de69e8.
