### ISSUE TITLE
Conda package for Mac OS?

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/pineappl#132]
Is it possible?
Because `nnpdf` needs Mac OS apparently?

**Comment by scarlehoff** [comment]
It's a question for which I wish the answer were different...

**Comment by AleCandido** [comment]
Unfortunately, you know the answer to that question... and it's the same for N3PDF as well...

**Comment by cschwan** [comment]
I think @scarrazza went ahead with this here: https://github.com/conda-forge/pineappl-feedstock/pull/11.

**Comment by cschwan** [comment]
@scarlehoff @scarrazza what's the status of this Issue?

**Comment by scarrazza** [comment]
@cschwan can be closed, see https://anaconda.org/conda-forge/pineappl

**Comment by cschwan** [comment]
@scarrazza cheers!
