### ISSUE TITLE
Expose build information to Python

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/pineappl#136]
How about adding something like https://github.com/PyO3/maturin/issues/100 ? or as is written there https://github.com/PyO3/pyo3-built/

this would facilitate the debugging process ...

**Comment by AleCandido** [comment]
`pyo3-built` looks unnecessarily complex and too unmaintained.

I'd suggest to go for the first option, it looks perfect to me :)

**Comment by cschwan** [comment]
That's a good idea, I'll look into it!

**Comment by cschwan** [comment]
I tried adding

```
m.add("__version__", env!("CARGO_PKG_VERSION"))?;
```

in `src/lib.rs`, but this doesn't have an effect. It should add a variable `pineappl.__version__`, shouldn't it?

**Comment by felixhekhorn** [comment]
yes - you can check the available attributes with `dir` (in case it got bound somewhere else ...)

**Comment by felixhekhorn** [comment]
@cschwan the magic was just in the nesting of the layers (it got bound in `pineappl.pineappl`) - I reexposed it again on top level

**Comment by cschwan** [comment]
@felixhekhorn cheers!
