### ISSUE TITLE
Add converter for 'new' APPLgrids

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#160]
For the ATLAS and CMS single-inclusive jet and dijet NNLO grids available here:

- [ATLAS 7 TeV dijet](https://ploughshare.web.cern.ch/ploughshare/db/applfast/applfast-atlas-dijets-appl-arxiv-1312.3524/applfast-atlas-dijets-appl-arxiv-1312.3524.tgz)
- [CMS 7 TeV dijet](https://ploughshare.web.cern.ch/ploughshare/db/applfast/applfast-cms-dijets-appl-arxiv-1212.6660/applfast-cms-dijets-appl-arxiv-1212.6660.tgz)
- [ATLAS 8 TeV single-inclusive jets](https://ploughshare.web.cern.ch/ploughshare/db/applfast/applfast-atlas-incjets-appl-arxiv-1706.03192/applfast-atlas-incjets-appl-arxiv-1706.03192.tgz)
- [CMS 8 TeV single-inclusive jets](https://ploughshare.web.cern.ch/ploughshare/db/applfast/applfast-cms-incjets-appl-arxiv-1609.05331/applfast-cms-incjets-appl-arxiv-1609.05331.tgz)

Right now we can't convert them into PineAPPL grids because those are in a new file format, with a `.appl` suffix, which is incompatible with our version of APPLgrid: <https://github.com/NNPDF/external/tree/master/applgrid-1.4.70-nnpdf>.

**Comment by cschwan** [comment]
This depends on #161.

**Comment by cschwan** [comment]
With the new converters these work out of the box. Here's an example:

```console
cschwan@wtpp123 grids $ pineappl --silence-lhapdf import applfast-atlas-dijets-appl-arxiv-1312.3524-xsec000.appl applfast-atlas-dijets-appl-arxiv-1312.3524-xsec000.pineappl.lz4 NNPDF40_nnlo_as_01180
appl::grid() version 1.6.27 compiled Jul 30 2022
appl::grid() reading grid from file applfast-atlas-dijets-appl-arxiv-1312.3524-xsec000.appl     :  applgrid version 1.6.29 (transformed to 1.6.27)      :  grid generated with NNPDF31_nnlo_as_0118 : set 0
+----------------------------------------------+
| ATLAS dijet production at 7 TeV              |
| arxiv: 1312.3524                             |
| d2sigma/dm12/dys [fb/GeV]                    |
| anti-kT R=0.6                                |
| Table 10:  0.0 <= y* < 0.5                   |
|                                              |
| https://ploughshare.web.cern.ch              |
|                                              |
| please cite:                                 |
|  PoS RADCOR2017, 074 (2018)                  |
|  PRL 118, 072002 (2017)                      |
|  JHEP 10, 155 (2018)                         |
|  EPJ. C79, 845 (2019)                        |
|  EPJ. C66, 503 (2010)                        |
|  Proc. DIS 2012, 217 (2012)                  |
+----------------------------------------------+


appl::grid() read grid, size 1.44429 MB in 213.615 ms   trim in 1.479 ms
b    PineAPPL     APPLgrid     rel. diff
--+------------+------------+--------------
0   9.5741685e5  9.5741685e5  1.5543122e-15
1   3.7061744e5  3.7061744e5 -6.6613381e-16
2   1.4077513e5  1.4077513e5  1.1102230e-15
3   5.6582832e4  5.6582832e4 -1.4432899e-15
4   2.3159408e4  2.3159408e4 -1.1102230e-16
5   1.0422135e4  1.0422135e4 -3.3306691e-16
6   4.7894678e3  4.7894678e3  1.3322676e-15
7   2.2842040e3  2.2842040e3  2.2204460e-16
8   1.1109483e3  1.1109483e3    0.0000000e0
9   5.3681270e2  5.3681270e2 -1.8873791e-15
10  2.5508164e2  2.5508164e2 -5.5511151e-16
11  1.1910298e2  1.1910298e2  4.4408921e-16
12  5.8051300e1  5.8051300e1  2.2204460e-16
13  2.7500268e1  2.7500268e1 -1.6653345e-15
14  1.2987431e1  1.2987431e1 -5.5511151e-16
15  5.9537060e0  5.9537060e0  6.6613381e-16
16  2.7115592e0  2.7115592e0    0.0000000e0
17  1.2028974e0  1.2028974e0 -3.3306691e-16
18 5.0109534e-1 5.0109534e-1  2.2204460e-16
19 2.0040917e-1 2.0040917e-1  8.8817842e-16
20 2.0618094e-2 2.0618094e-2 -1.2212453e-15
```

```console
cschwan@wtpp123 grids $ pineappl obl --orders applfast-atlas-dijets-appl-arxiv-1312.3524-xsec000.pineappl.lz4
o  order
-+-------
0 O(as^2)
1 O(as^3)
2 O(as^4)
```

So they *do* contain the NNLO grids, but no scale-variation grids.

**Comment by AleCandido** [comment]
> So they _do_ contain the NNLO grids, but no scale-variation grids.

I'm already happy with NNLO grids :D (finally we're getting closer to retire K-factors)

**Comment by felixhekhorn** [comment]
> > So they _do_ contain the NNLO grids, but no scale-variation grids.
> 
> I'm already happy with NNLO grids :D (finally we're getting closer to retire K-factors)

In principle they should be calculable from the previous orders, right? [as they are for DIS](https://yadism.readthedocs.io/en/latest/theory/scale-variations.html#factorization) (of course now everything more complicated due to two PDFs)

**Comment by cschwan** [comment]
They should be, yes.

**Comment by AleCandido** [comment]
> In principle they should be calculable from the previous orders, right? [as they are for DIS](https://yadism.readthedocs.io/en/latest/theory/scale-variations.html#factorization) (of course now everything more complicated due to two PDFs)

Everything -> factorization scale variation (renormalization scale is the exact same).
I wonder if it is actually possible from the grid itself, since they are events and you don't have the full analytic structure (I'm only confident that you can do it giving the *analytic expression* of lower orders), but maybe it is possible.

**Comment by cschwan** [comment]
@AleCandido let's talk here: https://github.com/N3PDF/pineappl/discussions/163.

**Comment by cschwan** [comment]
Hi @jamspandex , as far as I understand `.root` vs. `.appl` is (mostly) a change of the file format, to get rid of the ROOT dependency. Is that correct?

In the meantime we also don't really care that much anymore about the log-grids. They're best computed dynamically, as you said, although we consider that a job for different programs that then use the log-grids as the interface.

**Comment by jamspandex** [comment]
Hi, yes, exactly: the change to use the appl format was to allow applgrid to be compiled completely without root, and was mostly, but not completely, just a change to the persistent file format. After implementing it, we found that the new file format
was substantially faster to read and write than using root files, and the files themselves were significantly smaller. Applgrid can still read and write the root files, and if you simply read in an appl file and then immediately write it out as a root file, or vice versa, you can trivially convert between them, but the internal grid format does not use root. There is still an interface function that generates a root histogram for the convolution if you want it, but that disappears if you compile it without root. 

Thanks
Mark

**Comment by jamspandex** [comment]
Incidentally, in the applfast paper for the LHC grids, 

  https://arxiv.org/abs/2207.13735,  

we include the full dynamic scale variation that we use at NNLO. Is that what you mean ? 

Mark
