### ISSUE TITLE
Add support for APPLgrid conversion in `import`

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#161]
Added in commits 5941bf6dd4910c8dc996b2b6e92cbdad308d4172, af4047077da8686102f4f7defd7498fc9b5cb646, 42e4e16911b40e0c29986c6f715e525b12fcfc39, 052b077c530367d790b62664aa17e071fdaadae9 and cd854cbebe9826a41fbef20043f22b1c01c48253.

**Comment by cschwan** [comment]
@AleCandido @felixhekhorn could you give this a try? Note the [installation instructions](https://n3pdf.github.io/pineappl/docs/installation.html#optional-applgrid-converter). This should work just as fine as the old converter, and even a bit faster because we no longer need to guess the `reweight` parameters thanks to commit 42e4e16911b40e0c29986c6f715e525b12fcfc39. Let me know if there's anything that I can improve.

**Comment by AleCandido** [comment]
I guess I need root...

This week I'm at conference, but I'll try to do it as soon as possible on `dom`, I guess there there might already be an installed instance of root.

**Comment by cschwan** [comment]
`dom` has root!

**Comment by cschwan** [comment]
The real advantage of these changes are that we no longer restricted to use our NNPDF-modified version of APPLgrid; we can use the most recent version of it and also upgrade it in the future. I checked that the entire <https://github.com/NNPDF/applgrids> repository converts, and it seems that it even supports the photon grids out of the box.

**Comment by felixhekhorn** [comment]
Why do you need the `APPL_IGRID_DIR` variable? can't you expect it to be in `CPATH` (which I believe [should be the default c/c++ search path](https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html) )? or in case you can't maybe the example should use `pkgconfig`? Otherwise people might be confused "where did I install it again" and if you consider experimentalists running this then the installation might be somewhere far away (meaning out of control)

**Comment by cschwan** [comment]
Instead of `APPL_IGRID_DIR` you can indeed also use `CPATH` (if your compiler supports it). You can't use `pkg-config` because APPLgrid doesn't support it and in any case this header isn't installed, it's part of the private interface (that's why it is in the `src` directory).

The NNPDF-modified APPLgrid solved the same problem by making all the private headers public, but in this way every version you'd like to support you have to patch, and that's too fragile. `APPL_IGRID_DIR` isn't the best approach, but the least worst, in my opinion.

**Comment by AleCandido** [comment]
Ok, I see it is unpleasant, but I guess I agree with @cschwan at this point. You don't want to forever patch APPLgrid...
On the other side, if you are not the one that installed APPLgrid, most likely you're also not the guy that is going to make this non-minimal installation of PineAPPL as well.

**Comment by cschwan** [comment]
If there's any problem with the importer please open a separate Issue.
