### ISSUE TITLE
Add Arch User Repository badge

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/pineappl#41]
Hi, I just updated a PKGINFO to the Arch user repository: https://aur.archlinux.org/packages/pineappl/
mainly for my own convenience but I thought it would be nice to let you know: [![AUR](https://img.shields.io/aur/version/pineappl)](https://aur.archlinux.org/packages/pineappl)

This package installs also the python package.

I tried this package in the PR that @scarrazza added in vegasflow: https://github.com/N3PDF/vegasflow/pull/56 and seems to work.

**Comment by cschwan** [comment]
Thanks, let me add the badge to the README.

**Comment by cschwan** [comment]
Implemented in commit d93c51d69577b606fddac3e186c2e5351ff322ac.
