### ISSUE TITLE
Improve Python interface

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#71]
- [x] remove old Python interface
- [x] write github action for automatically uploading to PyPI whenever a release is published df7c8b556f006e91e091f86b54b958144c4aac88 - 88b78125e93addc0b753f714ff8533cfd6aa0572
- [x] change `convolute_eko` to return `FkTable` instead of `Grid`
- [x] ~~minimize the use of `unwrap`~~ I'm deferring this to a later stage
- [x] improve test coverage
- [x] make the old Python example working again 31ef6d3213bf625a814fea2a333846a914ad6d84
- [x] publish Python documentation using `.readthedocs.yml` https://github.com/N3PDF/pineappl/commit/ed0c9d6680daa9b9e6318c4fd9d29137b60a770c
- [x] improve `pineappl_py/README.md`

**Comment by felixhekhorn** [comment]
test coverage mostly done in https://github.com/N3PDF/pineappl/commit/baa6e9247e03edf01d2d9574b27c6a2722dc10e0

**Comment by AleCandido** [comment]
> test coverage mostly done in [baa6e92](https://github.com/N3PDF/pineappl/commit/baa6e9247e03edf01d2d9574b27c6a2722dc10e0)

Most likely @cschwan meant the coverage shown by the badge, and that takes only care about the rust files (see codecov).

**Comment by cschwan** [comment]
> _python_ test coverage mostly done in [baa6e92](https://github.com/N3PDF/pineappl/commit/baa6e9247e03edf01d2d9574b27c6a2722dc10e0)

That's what I meant, the Rust code coverage is a separate concern.

**Comment by AleCandido** [comment]
The better :)

**Comment by felixhekhorn** [comment]
> change convolute_eko to return FkTable instead of Grid

I started to address this in https://github.com/N3PDF/pineappl/commit/75055fd9471a764d34e7d902e176fc0c4578afdd I'm not sure this is done, yet

**Comment by AleCandido** [comment]
>     * [ ]  write github action for automatically uploading to PyPI whenever a release is published [df7c8b5](https://github.com/N3PDF/pineappl/commit/df7c8b556f006e91e091f86b54b958144c4aac88) - [88b7812](https://github.com/N3PDF/pineappl/commit/88b78125e93addc0b753f714ff8533cfd6aa0572)

Just waiting to switch:

- TestPyPI `->` PyPI
- `workflow_dispatch` `->` `on: release`

in the [workflow] https://github.com/N3PDF/pineappl/blob/master/.github/workflows/wheels.yml

**Comment by AleCandido** [comment]
We are now releasing even windows wheels with 54e9c55b83676a693f9d1256dcd8746ecd6df0cd

Now polishing the workflow, since looks like:
- in order to get multiple cpython wheels on `macOS` you need to run `maturin` with different python interpreters available (so you need a matrix job in order to rerun a job for eachl cpython wanted)
- on `windows` it behaves like `manylinux`: single job required to build many wheels (cpython 3.6, 3.7, 3.8, 3.9), setup python is not even required

**Comment by AleCandido** [comment]
`deploy-windows` actually polished in a0b17fe3cbc15162a68f91517cccd4933e8ef03e

**Comment by AleCandido** [comment]
> * [ ]  make the old Python example working again [31ef6d3](https://github.com/N3PDF/pineappl/commit/31ef6d3213bf625a814fea2a333846a914ad6d84)

I believe this has been solved in the commit I put by @felixhekhorn, can you confirm?

**Comment by cschwan** [comment]
> > * [ ]   make the old Python example working again [31ef6d3](https://github.com/N3PDF/pineappl/commit/31ef6d3213bf625a814fea2a333846a914ad6d84)
> 
> I believe this has been solved in the commit I put by @felixhekhorn, can you confirm?

Yes, works flawlessly!

**Comment by cschwan** [comment]
What's the status of .readthedocs.yml? The badge in README.md says it's not working. Is it possible to put this file into the pineappl_py subfolder (where it belongs)?

**Comment by cschwan** [comment]
I fixed `.readthedocs.yml` in commits 3e57f893a6a7879e1a63581864d366270544a93a and 56815e767173578a9148c94c6cf9263d24ca777c so that it actually triggers the build, nevertheless it still fails later on: https://readthedocs.org/projects/pineappl/builds/14840270/. It seems that cargo is missing, @AleCandido @felixhekhorn do you have any idea how to fix it?

**Comment by AleCandido** [comment]
I actually switched the workflow to target the official PyPI, now you can keep going @cschwan (we did whatever was possible to test it ahead of time, now I hope it should work out of the box).
You should be able just to make a release (we already deployed current version on testPyPI, but the two are completely independent), but for consistency I would make a new tag and start with beta versions.

I'm going to investigate readthedocs, I understand the problem and I already looked for something similar, but I don't remember perfectly what I found...

**Comment by AleCandido** [comment]
No way with readthedocs, see [note about C dependencies](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules), that is pointed by the generic [FAQ on install dependencies](https://docs.readthedocs.io/en/stable/faq.html#my-documentation-requires-additional-dependencies).

Essentially on readthedocs only python (i.e. PyPI) dependencies are allowed.

The alternative is to switch docs on github pages, building them in a workflow (we'll put at something like https://n3pdf.github.io/pineappl/pydocs).

**Comment by cschwan** [comment]
> I actually switched the workflow to target the official PyPI, now you can keep going @cschwan (we did whatever was possible to test it ahead of time, now I hope it should work out of the box).
> You should be able just to make a release (we already deployed current version on testPyPI, but the two are completely independent), but for consistency I would make a new tag and start with beta versions.

OK, in that case I'm going to release a beta version.

**Comment by cschwan** [comment]
> No way with readthedocs, see [note about C dependencies](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules), that is pointed by the generic [FAQ on install dependencies](https://docs.readthedocs.io/en/stable/faq.html#my-documentation-requires-additional-dependencies).
> 
> Essentially on readthedocs only python (i.e. PyPI) dependencies are allowed.
> 
> The alternative is to switch docs on github pages, building them in a workflow (we'll put at something like https://n3pdf.github.io/pineappl/pydocs).

I read the same pages, but there's support for Conda in RTD, and in conda-forge there's a Rust package: https://anaconda.org/conda-forge/rust. Can we use that? If not, we'll host the documentation ourselves.

**Comment by cschwan** [comment]
Seems to have worked: https://pypi.org/project/pineappl/0.5.0_beta/

**Comment by cschwan** [comment]
I managed to make a bit of progress using conda, see commit 4a2a8bba2fd70e186d9d167eac632a688bd8cecd, but the build still fails: https://readthedocs.org/projects/pineappl/builds/14842785/.

**Comment by cschwan** [comment]
> Seems to have worked: https://pypi.org/project/pineappl/0.5.0_beta/

@AleCandido It doesn't seem to work on my new computer:

```
$ pip3 install --pre --user pineappl
Collecting pineappl
  Using cached https://files.pythonhosted.org/packages/fa/22/acabc45e0d29ea12b7eccdb62025f1b082931d8f054b296d643687996d52/pineappl-0.5.0_beta.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-z8w4889t/pineappl/setup.py'
```

**Comment by felixhekhorn** [comment]
agreed - can you trick some additional pip arguments into `path`?

https://github.com/N3PDF/pineappl/blob/4a2a8bba2fd70e186d9d167eac632a688bd8cecd/.readthedocs.yml#L11

**Comment by AleCandido** [comment]
Maybe you're right and it's just possible with conda, but unfortunately I'm not familiar with it. I will have a look myself in the next few days, if possible let's try to make it work, otherwise `gh-pages` is always an option.

**Comment by cschwan** [comment]
@AleCandido I'm pretty sure that @felixhekhorn and I solved the problem now. We just need an [environment variable](https://docs.readthedocs.io/en/stable/environment-variables.html) `PIP_USE_FEATURE=in-tree-build` in the readthedocs configuation of this repository, and then it should work. However, @scarrazza has to do it because we don't have the rights.

**Comment by cschwan** [comment]
We get a different build error now, something is wrong with sphinx: https://readthedocs.org/projects/pineappl/builds/14844451/.

**Comment by felixhekhorn** [comment]
my bad - fixed in https://github.com/N3PDF/pineappl/commit/bf121b6821e6ad977770070680415e71bb3b8bb5

**Comment by cschwan** [comment]
There are more errors; apparently it can't find bibtex: https://readthedocs.org/projects/pineappl/builds/14844604/.

**Comment by felixhekhorn** [comment]
@cschwan @AleCandido :tada: [went through](https://pineappl.readthedocs.io/en/latest/)

**Comment by felixhekhorn** [comment]
> @cschwan @AleCandido tada [went through](https://pineappl.readthedocs.io/en/latest/)

*sigh* I was so happy I ticked the item prematurely - this is not working (yet) we're missing all the PyO3 stuff, i.e. the `pineappl.pineappl` module ... https://pineappl.readthedocs.io/en/latest/modules/pineappl/pineappl.html

**Comment by felixhekhorn** [comment]
I'm giving up for today ... we need to fix
```
💥 maturin failed
  Caused by: You need to be inside a virtualenv or conda environment to use develop (neither VIRTUAL_ENV nor CONDA_PREFIX are set). See https://virtualenv.pypa.io/en/latest/index.html on how to use virtualenv or use `maturin build` and `pip install <path/to/wheel>` instead.
```
[here](https://readthedocs.org/projects/pineappl/builds/14845424/)

and we do have a conda env around ...

I'm also slightly concerned that we're too late - because we're already *inside* sphinx

**Comment by AleCandido** [comment]
> > I managed to make a bit of progress using conda, see commit [4a2a8bb](https://github.com/N3PDF/pineappl/commit/4a2a8bba2fd70e186d9d167eac632a688bd8cecd), but the build still fails: https://readthedocs.org/projects/pineappl/builds/14842785/.
> 
> That's probably the following Issue: https://github.com/PyO3/maturin/issues/330.

Sorry not to have followed updates, I will check everything tomorrow.

Just to make some progress: I'm pretty sure the reason might be different, because in the quoted issue the problem is with the build pipeline triggered by `pip install .`, indeed pip is triggering the build system looking into `pyproject.toml`, and then there will be a problem with relative paths handling there. Instead we're directly using `maturin`, and fortunately nothing happened.

In your case all the build has already happened somewhere else (in the github workflow), and then the problem is not to make a binary wheel, but to resolve and install an existing one.
Could you share some details on your new system? (I'm also curious why your **new** computer is coming with python3.7, but for me it is good since you're testing another corner)

**Comment by AleCandido** [comment]
> I'm giving up for today ... we need to fix
> 
> ```
> 💥 maturin failed
>   Caused by: You need to be inside a virtualenv or conda environment to use develop (neither VIRTUAL_ENV nor CONDA_PREFIX are set). See https://virtualenv.pypa.io/en/latest/index.html on how to use virtualenv or use `maturin build` and `pip install <path/to/wheel>` instead.
> ```
> 
> [here](https://readthedocs.org/projects/pineappl/builds/14845424/)
> 
> and we do have a conda env around ...
> 
> I'm also slightly concerned that we're too late - because we're already _inside_ sphinx

If you read a few lines above there is the answer to your doubt:
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>
```

Meaning: maturin is failing because conda failed in before. Why conda failed, this I don't know (yet)

**Comment by AleCandido** [comment]
A proposal solution for the RTD issue might be the following: since `environment.yml` contains just a few dependencies

https://github.com/N3PDF/pineappl/blob/716abc8a0e628575fb134d0fc7c3b90b6d8656d1/pineappl_py/environment.yml#L4-L7

we can replace them with `apt` and `pip` (maybe):
- `sphinxcontrib-bibtex` and `maturin` have PyPI packages we can just use `pip`
- for [`rust`](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=rust&searchon=names) (and even [`cargo`](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=cargo&searchon=names)) there should be ubuntu packages 

Then maybe we can skip `conda` at all.

**Comment by cschwan** [comment]
I can read the documentation now, so does it mean it's working?

**Comment by cschwan** [comment]
> In your case all the build has already happened somewhere else (in the github workflow), and then the problem is not to make a binary wheel, but to resolve and install an existing one. Could you share some details on your new system? (I'm also curious why your **new** computer is coming with python3.7, but for me it is good since you're testing another corner)

It's a debian 10 machine, which isn't too old. Debian 11 (with Python 3.9) has only been released last month. How much work is it to add Python 3.7 support?

**Comment by felixhekhorn** [comment]
> I can read the documentation now, so does it mean it's working?

unfortunately no ...

> _sigh_ I was so happy I ticked the item prematurely - this is not working (yet) we're missing all the PyO3 stuff, i.e. the `pineappl.pineappl` module ... https://pineappl.readthedocs.io/en/latest/modules/pineappl/pineappl.html

**Comment by AleCandido** [comment]
As you said Debian 10 is quite common, I was not aware it was still on 3.7 (I would have expected 3.8, but that's not so strange considering it's Debian).

And the problem is that it should work, already, without any extra effort (just `pip install --pre pineappl`).
Since it's not the case we have to understand why it's not working, and I'm not sure it's 3.7 fault.

**Comment by cschwan** [comment]
> > I can read the documentation now, so does it mean it's working?
> 
> unfortunately no ...
> 
> > _sigh_ I was so happy I ticked the item prematurely - this is not working (yet) we're missing all the PyO3 stuff, i.e. the `pineappl.pineappl` module ... https://pineappl.readthedocs.io/en/latest/modules/pineappl/pineappl.html

I probably don't understand because I'm not too familiar with Python, what exactly is missing here?

**Comment by cschwan** [comment]
> [..] (I would have expected 3.8, but that's not so strange considering it's Debian).

:grin:

> 
> And the problem is that it should work, already, without any extra effort (just `pip install --pre pineappl`). Since it's not the case we have to understand why it's not working, and I'm not sure it's 3.7 fault.

Is it possible that there's interference with Python 2? It's still the default on Debian 10...

**Comment by AleCandido** [comment]
@cschwan write here your pip version and then try to upgrade it `pip install --upgrade pip`

Seems like the issue is known on [SO](https://stackoverflow.com/questions/51405580/pip-install-filenotfounderror-errno-2-no-such-file-or-directory)

**Comment by felixhekhorn** [comment]
> I probably don't understand because I'm not too familiar with Python, what exactly is missing here?

we're missing the PyO3 module, i.e. e.g. the documentation for `PyBinRemapper` (that is written in Rust)

**Comment by cschwan** [comment]
@AleCandido Indeed, that was the problem. My pip version was:

    pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

It works with 21.2.4!

**Comment by cschwan** [comment]
> > I probably don't understand because I'm not too familiar with Python, what exactly is missing here?
> 
> we're missing the PyO3 module, i.e. e.g. the documentation for `PyBinRemapper` (that is written in Rust)

Do we really want to document it? The user should not be able to directly work with the Rust parts, in fact they shouldn't know that there's Rust involved at all. But maybe we'd like to have it as internal documentation (developer documentation)?

**Comment by felixhekhorn** [comment]
> Do we really want to document it? The user should not be able to directly work with the Rust parts, in fact they shouldn't know that there's Rust involved at all. But maybe we'd like to have it as internal documentation (developer documentation)?

No, we need it because it holds all the crucial functions that are exposed to the user (remember our magic binding in `PyWrapper`) and hence we have to document it (and `maturin` is providing the documentation from below ...)

e.g. `PyGrid.bin_left()`

**Comment by AleCandido** [comment]
> @AleCandido Indeed, that was the problem. My pip version was:
> 
> ```
> pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
> ```
> 
> It works with 21.2.4!

So bad...

It's true that there are 3 majors between 18 and 21, and each one might break compatibility, but pip is iterating too fast on majors...

**Comment by cschwan** [comment]
> > Do we really want to document it? The user should not be able to directly work with the Rust parts, in fact they shouldn't know that there's Rust involved at all. But maybe we'd like to have it as internal documentation (developer documentation)?
> 
> No, we need it because it holds all the crucial functions that are exposed to the user (remember our magic binding in `PyWrapper`) and hence we have to document it (and `maturin` is providing the documentation from below ...)
> 
> e.g. `PyGrid.bin_left()`

In that case what do we think about explicitly wrapping every method to document them?

**Comment by cschwan** [comment]
@AleCandido @felixhekhorn Can you please review commits 2665c9bd550b22abb1d100b826cc21c600084804, 73b6a5fa2894ab70ebd7c360e434a14d769a96b9 and 43f39e3efee39d454d0b73c6d29a96e67672bdb6? These are changes will be needed by @scarlehoff. I'll do another beta release shortly after your OK.

**Comment by felixhekhorn** [comment]
@scarlehoff we also implemented the `FkTable.read` that we were talking about in https://github.com/N3PDF/pineappl/commit/a12338a845baf58678344f833c2aa7dfd46455c3 so you should use that one to read the FkTable

**Comment by felixhekhorn** [comment]
@cschwan we completed the RTD integration in https://github.com/N3PDF/pineappl/commit/ed0c9d6680daa9b9e6318c4fd9d29137b60a770c and now we have [`PyGrid.bin_left`](https://pineappl.readthedocs.io/en/latest/modules/pineappl/pineappl.html#pineappl.pineappl.PyGrid.bin_left) which otherwise the Python developers would not known (but they most likely need)

**Comment by cschwan** [comment]
Great! I'll prepare a new beta release in this case.

**Comment by AleCandido** [comment]
> Great! I'll prepare a new beta release in this case.

Wait one second, I'm going to add some defaults as requested by Juan

**Comment by scarlehoff** [comment]
Great, thank you guys very much.
I've decided to put the script @cschwan wrote yesterday for the cfactors exercise in a jupyter notebook https://github.com/NNPDF/tutorials/blob/master/pineappl/Create%20new%20cfactor%20files%20with%20pineappl%20-%20Pineappl%20python%20interface%20test%20case.ipynb in case you want to have a look at the use-case (cell [7] right now) or test before the release.

For simplicity, validphys-free relevant code:

```python
    pin = 'pineapplgrids/LHCB_DY_7TEV_940PB.pineappl.lz4'
    pdf = 'NNPDF31_nnlo_as_0118'
    pine = pineappl.grid.Grid.read(pin)
    lhapdf_pdf = lhapdf.mkPDF(pdf, 0)
    xf = lhapdf_pdf.xfxQ2
    a_s = lhapdf_pdf.alphasQ2
    tmp = pine.convolute(xf, xf, a_s)
    res_nlo_ew_raw.append(np.array(tmp))
```

**Comment by AleCandido** [comment]
I've finished with the defaults, now the `???` is simply empty, don't put anything, and it is correct.

However, thanks to Felix stubbornness even the docs are now working, so in case you need anything different from defaults you can read there.

**Comment by scarlehoff** [comment]
What do I get with the default? I want to separately get ew and qcd nlo

The docs say:

> Mask for selecting specific orders. The value True means the corresponding order is included. An empty list corresponds to all orders being enabled.

What is the order of the orders (heh)? [LO, NLO QCD, NLO EW]? (and how does they look in the return list)?

**Comment by AleCandido** [comment]
Maybe there is a problem: are you speaking of FkTables or Monte Carlo grids (i.e. after or before evolution)?

It's true that for Monte Carlo grids you can mask orders, and they are even slightly more complicated since they include scale variation (an order is a 4-tuple, you can see it on [pineappl docs](https://docs.rs/pineappl/0.4.1/pineappl/grid/struct.Order.html#fields)), for the time being you can find it with `pineappl orders <grid>` from command line (if needed we can expose later on in python).

If instead your question is about FkTables, then it's simply impossible. The orders in FkTables have already been folded by using alpha_s and alpha at generation time.

Which one of the two?

**Comment by scarlehoff** [comment]
I want to add the orders to the code I put [here](https://github.com/N3PDF/pineappl/issues/71#issuecomment-931177566
) so I can get the results (after convolution).

I'm not using scale variations. Right now after I used that code I get an array of results for `xs` where `xs = LO + NLO_QCD + NLO_EW`. The question is, how should I use to separate them.
More specifically, should I do:

```python
some_structure_with_all_info = pine.convolute(xf, xf, a_s, [True, True, True])
```
or
```python
LO = pine.convolute(xf, xf, a_s, [True, False, False])
NLO_EW = pine.convolute(xf, xf, a_s, [True, False, True])
NLO_QCD = pine.convolute(xf, xf, a_s, [True, True, False])
```

But anyway, I can find out as soon as the release is available.

**Comment by AleCandido** [comment]
If you want to separate them, you should do the second one.
Specifying all `True` is like no mask, you're not hiding any of them. The result is always a simple object (an array on bins).

As said above, for the order you have to use `pineappl orders`, but if this is an actual use case we can add it to the python library.

**Comment by scarlehoff** [comment]
Great thanks.

> As said above, for the order you have to use pineappl orders, but if this is an actual use case we can add it to the python library.

It is, I'm using it :P but for the time being I can obtain the same information with the code above so the current version works for me.

**Comment by cschwan** [comment]
> If you want to separate them, you should do the second one. Specifying all `True` is like no mask, you're not hiding any of them. The result is always a simple object (an array on bins).
> 
> As said above, for the order you have to use `pineappl orders`, but if this is an actual use case we can add it to the python library.

Yes, we should add the method `orders` to the Python interface. In general, the order of the (perturbative) orders (ha!) is arbitrary, so we need this method.

**Comment by felixhekhorn** [comment]
@scarlehoff @cschwan `orders()` is exposed here: https://github.com/N3PDF/pineappl/commit/d7d63b7c0d575207b621a849cb3f9ad213fea6b8

**Comment by cschwan** [comment]
@felixhekhorn @scarlehoff Thanks, I published a new release that should appear on PyPI soon.

**Comment by felixhekhorn** [comment]
@cschwan 
> improve pineappl_py/README.md

in https://github.com/N3PDF/pineappl/commit/02c4f452e3f30c9f1aac36bf586474b12f731c59 I moved the installation instructions to the docs (as we discussed) - so the thing is almost empty now, is this ok?

**Comment by cschwan** [comment]
> @cschwan
> 
> > improve pineappl_py/README.md
> 
> in [02c4f45](https://github.com/N3PDF/pineappl/commit/02c4f452e3f30c9f1aac36bf586474b12f731c59) I moved the installation instructions to the docs (as we discussed) - so the thing is almost empty now, is this ok?

I'd say that's fine. I suggest we'll further improve the README as we go along.

**Comment by cschwan** [comment]
I'm closing this Issue now. For any further discussion let's open a new one.
