### ISSUE TITLE
FkTable.table raises unexpected error

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/pineappl#77]
As reported by @scarlehoff running the following on [the attached FkTable](https://github.com/N3PDF/pineappl/files/7354104/213-HERA_NC_318GEV_EP_SIGMARED.zip) does not work, and it raises.
```py
In [2]: from pineappl.fk_table import FkTable
  ...: pine_file = "fktables/213-HERA_NC_318GEV_EP_SIGMARED.pineappl"
  ...: pine_fk = FkTable.read(pine_file)
  ...: pine_fk.table()
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-2-b66371a3a195> in <module>
     2 pine_file = "fktables/213-HERA_NC_318GEV_EP_SIGMARED.pineappl"
     3 pine_fk = FkTable.read(pine_file)
----> 4 pine_fk.table()

PanicException: ndarray: index [0, 1, 2, 0] is out of bounds for array of shape [485, 14, 0, 0]
```

Most likely we have a `subgrid(0, 0, 0)` empty, and then the subgrid allocated has dimension (#bins, #lumis, 0, 0), and it fails as soon as it iterates over the following subgrids.

https://github.com/N3PDF/pineappl/blob/ad6073b15bba36971e8475b7fb637b1f75464d47/pineappl/src/fk_table.rs#L55-L72

**Comment by cschwan** [comment]
@scarlehoff @AleCandido commit eb2af60a69fd9e979a77d822fef904397e46d816 should fix this problem in the general case. Could you please let me know if it works?

**Comment by scarlehoff** [comment]
Yes, it works with some of the unoptimized grids as well.

One problem though is that the `convolute` method is not working any more. I'll try to write a MWE and open an new issue.

**Comment by cschwan** [comment]
> One problem though is that the `convolute` method is not working any more. I'll try to write a MWE and open an new issue.

I think the problem is commit 4e40743929483f9e670069238e7368b77634ba76, which now requires the PDFs that you pass to PineAPPL are in the flavour basis, irrespectively of what basis the grid is in.
